### ISSUE TITLE
Update `source_gen`

### ISSUE THREAD

**Issue by lishaduck** [Milad-Akarie/auto_route_library#2124]
`source_gen` v2 is now out, with support for `dart_style` v3, analyzer v7, and more.
A bump would be much appreciated, @Milad-Akarie.
Happy to send in a PR.

**Comment by Milad-Akarie** [comment]
done

**Comment by agenthesh** [comment]
@Milad-Akarie Looks like you forgot to bump the actual versions of packages?

**Comment by Milad-Akarie** [comment]
@agenthesh good catch, fixed
