### ISSUE TITLE
RangeError when running build

### ISSUE THREAD

**Issue by ResoDev** [Milad-Akarie/auto_route_library#3]
Hello!
Even a simple widget like this:
```
import 'package:auto_route/auto_route_annotation.dart';
import 'package:flutter/material.dart';

@AutoRoute()
class PolicySelectorPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container();
  }
}
```

Causes a build error:
```
[SEVERE] auto_route_generator:autoRouteGenerator on lib/features/policies/ui/pages/policy_selector_page.dart:
Error running AutoRouteGenerator
RangeError: Value not in range: -1
```

I am running Flutter 1.9.1+hotfix.6 and package versions 0.111 for auto_route, 0.1.2 for auto_route_generator.

**Comment by Milad-Akarie** [comment]
@ResoDev  hey! I couldn't reproduce the error. There was an issue with the analyzer package though and I just fixed that. Can you please try again?

**Comment by ResoDev** [comment]
Unfortunately, updating to 0.1.3 and even removing all other dev_dependencies doing code generation didn't help. Still the same issue.

**Comment by Milad-Akarie** [comment]
I've never ran into this error during development and I can't reproduce the error now. Can you please share a gist or something?

**Comment by ResoDev** [comment]
I'll try it in a clean new project and let you know ASAP. It doesn't make any sense at all.

**Comment by kuhnroyal** [comment]
Maybe run the generation with `-v` to get a stack trace.
The only operations producing a RangeError seem to be some path replacements with `lib`.

**Comment by Milad-Akarie** [comment]
@ResoDev  I've used a totally different approach in the new version 0.2.0 be sure to check it out and share your thoughts.

**Comment by ResoDev** [comment]
I'm happy to announce that with the approach taken in 0.2.0 (and hopefully beyond 😅), there are no crashes. Great library, keep it up!
