### ISSUE TITLE
AutoRouteGuard not picking up direct url changes in version 2.1.0

### ISSUE THREAD

**Issue by CassiusPacheco** [Milad-Akarie/auto_route_library#517]
Hi there,

with the latest update of version 2.1.0, `AutoRouteGuard` has changed to a new API which works fine when dealing with `router.push` methods, but if the user types into the URL browser an URL, the guard isn't picking it up anymore how it used to in the previous versions.

The code below used to work correctly in the previous version, but now it does not get called on manual URL changes:

```dart
const onboardingRoutes = AutoRoute(
  path: 'onboarding',
  page: EmptyRouterPage,
  name: 'OnboardingRoute',
  initial: true,
  children: [
    AutoRoute(
      path: '',
      page: OnboardingStepsPage,
      name: 'OnboardingStep01PageRoute',
    ),
    AutoRoute(
      path: 'step/:step',
      page: OnboardingStepsPage,
      name: 'OnboardingStepsPageRoute',
      guards: [AuthGuard],
    ),
  ],
);

class AuthGuard extends AutoRouteGuard {
  late final OnboardingStepGuardUseCase _onboardingStepGuardUseCase;

  AuthGuard() : _onboardingStepGuardUseCase = ServiceLocator().resolve();
  AuthGuard.named(this._onboardingStepGuardUseCase);

  @override
  void canNavigate(NavigationResolver resolver, StackRouter router) {
    final step = resolver.route.pathParams.optInt('step');

    if (step == null) {
        resolver.next(false);
        return;
    }

    _onboardingStepGuardUseCase(StepParam(step))
        .take(1)
        .first
        .then(resolver.next);
  }
}
```

**Comment by theweiweiway** [comment]
Hm. A very similar scenario where I was hitting the url directly with a guard was working for me.

It's here: https://www.github.com/theweiweiway/uxr/tree/master/nav2-usability%2Fscenario_code%2Flib%2Fdynamic-linking%2Fdynamic_linking_auto_route.dart

Maybe it will help

**Comment by CassiusPacheco** [comment]
It's very inconsistent. Sometimes it gets picked up, others it doesn't. I need to do a full reload in order to make it get picked up, but the problem is that it already allowed the user to access resources that shouldn't be allowed.

**Comment by Milad-Akarie** [comment]
@CassiusPacheco resolver.next should only be called once. the navigation will **Pause** until you resolve with either false which means abort or true witch means continue/resume
 if this is true then the resolver has already been resolved with abort 
  ` if (step == null) resolver.next(false);`
so I believe if you remove this line your code will work as expected.

p.s in the new version 2.1.1 `canNavigate` becomes `onNavigation` because it makes more sense, sorry for forgetting that

**Comment by CassiusPacheco** [comment]
Ops, I had noticed that and fixed it in my code but forgot to update it here. The issue still remains, not sure why. The first time I type in the url it gets picked up, but the following times it doesn't, until I actually reload everything.

**Comment by Milad-Akarie** [comment]
@CassiusPacheco you mean this route 
```
 AutoRoute(
      path: 'step/:step',
      page: OnboardingStepsPage,
      name: 'OnboardingStepsPageRoute',
      guards: [AuthGuard],
    ),
```
is pushed and canNavigate is not called?

**Comment by CassiusPacheco** [comment]
Yes, that one. It canNavigate always get called on router.push, but going on the browser URL (Flutter Web) and typing steps /onboarding/step/4, for example, only the first typing works. Any subsequent steps I type in won’t call canNavigate again

**Comment by Milad-Akarie** [comment]
@CassiusPacheco should be fixed in version 2.2.0 please confirm and close.
Thank you for reporting, it was a bug.

**Comment by CassiusPacheco** [comment]
It's fixed! Thanks for the swift fix <3
