### ISSUE TITLE
White screen on web after hot reload

### ISSUE THREAD

**Issue by funyin** [Milad-Akarie/auto_route_library#584]
With hot reloading on web the screen flashes the actual layout the replaced by a white screen.

Flutter doctor
```
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19041.685], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)

```

**Comment by funyin** [comment]
Fixed-  this issue was caused by putting the reference to the router in the build method

**Wrong**
'''
@override
  Widget build(BuildContext context) {
  var appRouter = AppRouter();
  return MaterialApp.router();
  }
'''

**Correct**
'''
var appRouter = AppRouter();

@override
  Widget build(BuildContext context) {
  return MaterialApp.router();
  }
'''

**Comment by arifikhsan** [comment]
> Fixed- this issue was caused by putting the reference to the router in the build method
> 
> **Wrong**
> 
> ```
> @override
>   Widget build(BuildContext context) {
>   var appRouter = AppRouter();
>   return MaterialApp.router();
>   }
> ```
> 
> **Correct**
> 
> ```
> var appRouter = AppRouter();
> 
> @override
>   Widget build(BuildContext context) {
>   return MaterialApp.router();
>   }
> ```

thanks man, you saved my life ❤️

**Comment by Vladeouz** [comment]
Actually, i still dont understand, i have put the appRouter outside the build method, but eveytime i save my code, it make the current screen as the init route, and remove the leading back button on the appbar.
